<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1dxjbK1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1dxjbK1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1dxjbK1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1dxjbK1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1dxjbK1\App_KernelDevDebugContainer([
    'container.build_hash' => '1dxjbK1',
    'container.build_id' => '42c19104',
    'container.build_time' => 1611597546,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1dxjbK1');
